//Acciones Obtener Datos Dashboard
export const GET_TOTALES = 'GET_TOTALES'
export const GET_SOLICITUDES_POR_REGIONALES = 'GET_SOLICITUDES_POR_REGIONALES'
export const GET_SOLICITUDES_POR_CATEGORIA =  'GET_SOLICITUDES_POR_CATEGORIA'
export const GET_SOLICITUDES_POR_TRAMITE = 'GET_SOLICITUDES_POR_TRAMITE'
export const GET_LISTADO_SOLICITUDES = 'GET_LISTADO_SOLICITUDES'

//Acciones Sesion Usuarios
export const INICIAR_SESION_USUARIO = 'INICIAR_SESION_USUARIO'
export const CERRAR_SESION_USUARIO = 'CERRAR_SESION_USUARIO'
export const LOADING = 'LOADING'
export const USUARIO_ERROR = 'USUARIO_ERROR'